### ISSUE TITLE
Module not found: Can't resolve 'fs' 

### ISSUE THREAD

**Issue by TidyIQ** [sindresorhus/locate-path#5]
I'm using the popular [find-up](https://www.npmjs.com/package/find-up) npm package which has this as a dependency. When I attempt to run my app I get:

```
[ error ] ./node_modules/locate-path/index.js
Module not found: Can't resolve 'fs' in 'C:\...\node_modules\locate-path'
```

**Comment by sindresorhus** [comment]
`fs` is a built-in module in Node.js. I guess you're using Webpack and not using it correctly. Regardless, this is definitely not a problem with this module or `find-up`.

**Comment by TidyIQ** [comment]
I'm not using Webpack but I am using Next.js, which uses Webpack. I guess the issue is with them in that case. Thanks for the quick reply.
