### ISSUE TITLE
Reject promise if no paths exist

### ISSUE THREAD

**Issue by polarstoat** [sindresorhus/locate-path#8]
I'm wondering whether it could be useful to return a rejected promise if none of the provided paths exist.

I've found myself using something like the below snippet a few times, and found myself asking whether none of the provided paths existing should be considered an error.
```js
locatePath(paths).then((result) => {
  if (typeof result === 'undefined') return Promise.reject(new Error('No paths found!'));

  return Promise.resolve(result);
});
```

I find this approach easier as I don't need to check for `undefined` when using the result, and I can better separate the logic for dealing with no paths being found with a `.catch()`.

Perhaps this is an anti-pattern or I'm otherwise missing something, but I'd welcome any thoughts/ideas as to if this should be considered an error or not.

**Comment by sindresorhus** [comment]
I can understand how you would want to simplify it, but you are only thinking of your specific use-case. There are many use-cases where you'd just want to fall back to some other value. `(await locatePath(…)) ?? fallback`. Let's say we did throw an error, what would the error message be? it really depends on the use-case. Is it going to be shown to the user? What if it's used in a place where it needs to be localized. Returning `undefined` is generally better for cases like this.
